# Generated by Django 3.2.4 on 2021-06-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('modelwithcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.modelwithcategory')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='static/img/brands/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/brands/')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
            bases=('base.modelwithcategory',),
        ),
    ]
