# Generated by Django 3.2.4 on 2021-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to='static/img/cases/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='case',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='static/img/cases/'),
        ),
    ]
