# Generated by Django 3.2.4 on 2021-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210615_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(default=None, upload_to='static/img/cases/', verbose_name='Изображение'),
        ),
    ]
