# Generated by Django 3.2.4 on 2021-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to='static/img/cases/', verbose_name='Изображение'),
        ),
    ]
