# Generated by Django 3.2.4 on 2021-06-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('modelwithcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.modelwithcategory')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('job', models.CharField(max_length=64, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='static/img/masters/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/masters/')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Наши мастера',
            },
            bases=('base.modelwithcategory',),
        ),
        migrations.CreateModel(
            name='MasterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=64, verbose_name='Умение')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master', verbose_name='Мастер')),
            ],
        ),
    ]
