# Generated by Django 3.2.4 on 2021-06-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReview',
            fields=[
                ('modelwithcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.modelwithcategory')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='static/img/reviews/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/reviews/')),
            ],
            options={
                'verbose_name': 'Фотоотзыв',
                'verbose_name_plural': 'Фотоотзывы',
            },
            bases=('base.modelwithcategory',),
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('modelwithcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.modelwithcategory')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='static/img/reviews/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/reviews/')),
                ('video_url', models.CharField(max_length=64, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видеоотзыв',
                'verbose_name_plural': 'Видеоотзывы',
            },
            bases=('base.modelwithcategory',),
        ),
    ]
