# Generated by Django 3.2.4 on 2021-06-16 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20210615_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=64, verbose_name='Услуга')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создание заказа')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='Почта')),
                ('description', models.TextField(blank=True, max_length=64, verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создание заказа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
